// =============================================================================
// ontology.cypher  —  M0 ontology backbone seed
//
// Seeds anchor terms (`:OntologyTerm + :<Source>Class | :<Source>Property`),
// the F.3 Role vocabulary, SchedulerKind nodes, effective-dated BusinessSegments
// under :Company JPMC, and a baseline DQ catalog (5 dimensions x 2 metrics).
//
// Idempotent. Safe to re-run.
//
// Namespaces (kept in sync with drydocs/ontology/namespaces.py):
//   dprod  https://ekgf.github.io/dprod#
//   dcat   http://www.w3.org/ns/dcat#
//   prov   http://www.w3.org/ns/prov#
//   dqv    http://www.w3.org/ns/dqv#
//   org    http://www.w3.org/ns/org#
//   swo    http://www.ebi.ac.uk/swo/
//   obi    http://purl.obolibrary.org/obo/
//   iao    http://purl.obolibrary.org/obo/
// =============================================================================


// ----- DPROD (data product ontology) -----------------------------------------
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#DataProduct"})
  SET n.label = "Data Product",
      n.notes = "A unit of consumable data, governed by ports + agreements.";
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#Port"})         SET n.label = "Port";
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#InputPort"})    SET n.label = "Input Port";
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#OutputPort"})   SET n.label = "Output Port";
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#DataContract"}) SET n.label = "Data Contract";
MERGE (n:OntologyTerm:DprodClass {iri:"https://ekgf.github.io/dprod#Agreement"})    SET n.label = "Agreement";
MERGE (n:OntologyTerm:DprodProperty {iri:"https://ekgf.github.io/dprod#hasInputPort"})   SET n.label = "has input port";
MERGE (n:OntologyTerm:DprodProperty {iri:"https://ekgf.github.io/dprod#hasOutputPort"})  SET n.label = "has output port";
MERGE (n:OntologyTerm:DprodProperty {iri:"https://ekgf.github.io/dprod#exposesDataset"}) SET n.label = "exposes dataset";


// ----- DCAT v3 ----------------------------------------------------------------
MERGE (n:OntologyTerm:DcatClass {iri:"http://www.w3.org/ns/dcat#Catalog"})      SET n.label = "Catalog";
MERGE (n:OntologyTerm:DcatClass {iri:"http://www.w3.org/ns/dcat#Dataset"})      SET n.label = "Dataset";
MERGE (n:OntologyTerm:DcatClass {iri:"http://www.w3.org/ns/dcat#Distribution"}) SET n.label = "Distribution";
MERGE (n:OntologyTerm:DcatClass {iri:"http://www.w3.org/ns/dcat#DataService"})  SET n.label = "Data Service";
MERGE (n:OntologyTerm:DcatClass {iri:"http://www.w3.org/ns/dcat#DataProduct"})  SET n.label = "DCAT Data Product (v3)";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#theme"})        SET n.label = "theme";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#contactPoint"}) SET n.label = "contact point";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#distribution"}) SET n.label = "distribution";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#accessURL"})    SET n.label = "access URL";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#downloadURL"})  SET n.label = "download URL";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#mediaType"})    SET n.label = "media type";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#keyword"})      SET n.label = "keyword";
MERGE (n:OntologyTerm:DcatProperty {iri:"http://www.w3.org/ns/dcat#endpointURL"})  SET n.label = "endpoint URL";


// ----- PROV-O / PROV-DM ------------------------------------------------------
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#Entity"})         SET n.label = "Entity";
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#Activity"})       SET n.label = "Activity";
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#Agent"})          SET n.label = "Agent";
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#Plan"})           SET n.label = "Plan";
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#Collection"})     SET n.label = "Collection";
MERGE (n:OntologyTerm:ProvClass {iri:"http://www.w3.org/ns/prov#SoftwareAgent"})  SET n.label = "Software Agent";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#used"})              SET n.label = "used";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#wasGeneratedBy"})    SET n.label = "was generated by";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#generated"})         SET n.label = "generated";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#hadMember"})         SET n.label = "had member";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#wasAttributedTo"})   SET n.label = "was attributed to";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#wasAssociatedWith"}) SET n.label = "was associated with";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#wasInformedBy"})     SET n.label = "was informed by";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#wasDerivedFrom"})    SET n.label = "was derived from";
MERGE (n:OntologyTerm:ProvProperty {iri:"http://www.w3.org/ns/prov#actedOnBehalfOf"})   SET n.label = "acted on behalf of";


// ----- DQV (data quality vocabulary) -----------------------------------------
MERGE (n:OntologyTerm:DqvClass {iri:"http://www.w3.org/ns/dqv#QualityMeasurement"}) SET n.label = "Quality Measurement";
MERGE (n:OntologyTerm:DqvClass {iri:"http://www.w3.org/ns/dqv#Metric"})             SET n.label = "Metric";
MERGE (n:OntologyTerm:DqvClass {iri:"http://www.w3.org/ns/dqv#Dimension"})          SET n.label = "Dimension";
MERGE (n:OntologyTerm:DqvClass {iri:"http://www.w3.org/ns/dqv#Category"})           SET n.label = "Category";
MERGE (n:OntologyTerm:DqvClass {iri:"http://www.w3.org/ns/dqv#QualityAnnotation"})  SET n.label = "Quality Annotation";
MERGE (n:OntologyTerm:DqvProperty {iri:"http://www.w3.org/ns/dqv#hasQualityMeasurement"}) SET n.label = "has quality measurement";
MERGE (n:OntologyTerm:DqvProperty {iri:"http://www.w3.org/ns/dqv#computedOn"})            SET n.label = "computed on";
MERGE (n:OntologyTerm:DqvProperty {iri:"http://www.w3.org/ns/dqv#isMeasurementOf"})       SET n.label = "is measurement of";
MERGE (n:OntologyTerm:DqvProperty {iri:"http://www.w3.org/ns/dqv#inDimension"})           SET n.label = "in dimension";
MERGE (n:OntologyTerm:DqvProperty {iri:"http://www.w3.org/ns/dqv#value"})                 SET n.label = "value";


// ----- ORG (W3C Organization) ------------------------------------------------
MERGE (n:OntologyTerm:OrgClass {iri:"http://www.w3.org/ns/org#Organization"})       SET n.label = "Organization";
MERGE (n:OntologyTerm:OrgClass {iri:"http://www.w3.org/ns/org#OrganizationalUnit"}) SET n.label = "Organizational Unit";
MERGE (n:OntologyTerm:OrgClass {iri:"http://www.w3.org/ns/org#FormalOrganization"}) SET n.label = "Formal Organization";
MERGE (n:OntologyTerm:OrgClass {iri:"http://www.w3.org/ns/org#Membership"})         SET n.label = "Membership";
MERGE (n:OntologyTerm:OrgClass {iri:"http://www.w3.org/ns/org#Role"})               SET n.label = "Role";
MERGE (n:OntologyTerm:OrgProperty {iri:"http://www.w3.org/ns/org#hasUnit"})       SET n.label = "has unit";
MERGE (n:OntologyTerm:OrgProperty {iri:"http://www.w3.org/ns/org#hasMember"})     SET n.label = "has member";
MERGE (n:OntologyTerm:OrgProperty {iri:"http://www.w3.org/ns/org#memberOf"})      SET n.label = "member of";
MERGE (n:OntologyTerm:OrgProperty {iri:"http://www.w3.org/ns/org#role"})          SET n.label = "role";
MERGE (n:OntologyTerm:OrgProperty {iri:"http://www.w3.org/ns/org#hasMembership"}) SET n.label = "has membership";


// ----- SWO anchor terms (SDLC subset) ---------------------------------------
//   Full SDLC subset (~250 terms) loads from ontology/reference/swo_sdlc_ontology.cypher
//   in the M0 follow-up step. The following are the high-frequency anchors
//   referenced by loaders and Streamlit pages.
MERGE (n:OntologyTerm:SwoClass {iri:"http://www.ebi.ac.uk/swo/SWO_0000001"})       SET n.label = "software";
MERGE (n:OntologyTerm:SwoClass {iri:"http://purl.obolibrary.org/obo/IAO_0000025"}) SET n.label = "programming language";
MERGE (n:OntologyTerm:SwoClass {iri:"http://www.ebi.ac.uk/swo/SWO_0000118"})       SET n.label = "Python";
MERGE (n:OntologyTerm:SwoClass {iri:"http://www.ebi.ac.uk/swo/SWO_0000124"})       SET n.label = "Shell";
MERGE (n:OntologyTerm:SwoClass {iri:"http://www.ebi.ac.uk/swo/SWO_0000012"})       SET n.label = "Java";
MERGE (n:OntologyTerm:SwoClass {iri:"http://www.ebi.ac.uk/swo/SWO_0000126"})       SET n.label = "SQL";
MERGE (n:OntologyTerm:SwoClass {iri:"http://purl.obolibrary.org/obo/OBI_0200000"}) SET n.label = "data transformation";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0040005"}) SET n.label = "is executed in";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0000741"}) SET n.label = "is encoded in";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0000740"}) SET n.label = "implements";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0000086"}) SET n.label = "has specified data input";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0000087"}) SET n.label = "has specified data output";
MERGE (n:OntologyTerm:SwoProperty {iri:"http://www.ebi.ac.uk/swo/SWO_0000150"}) SET n.label = "uses platform";


// ----- OpenLineage label vocabulary -----------------------------------------
//   OL doesn't publish OWL; we record canonical names for cross-reference.
MERGE (n:OntologyTerm:OlClass {iri:"https://openlineage.io/spec/Run"})     SET n.label = "OL Run";
MERGE (n:OntologyTerm:OlClass {iri:"https://openlineage.io/spec/Job"})     SET n.label = "OL Job";
MERGE (n:OntologyTerm:OlClass {iri:"https://openlineage.io/spec/Dataset"}) SET n.label = "OL Dataset";


// ----- Roles (F.3) ----------------------------------------------------------
//   Eight roles. SEAL contributes the operate-side five; PAT contributes the
//   dev-side three. Same Employee can hold multiple Memberships across both.
MERGE (r:Role {name:"App Owner"})          SET r.source = "SEAL", r.description = "Application owner of record (SEAL).";
MERGE (r:Role {name:"Data Owner"})         SET r.source = "SEAL", r.description = "Data owner accountable for the application's data (SEAL).";
MERGE (r:Role {name:"L2 Operate Manager"}) SET r.source = "SEAL", r.description = "Tier-2 operate manager. Drives support-team derivation (F.4).";
MERGE (r:Role {name:"Risk Manager"})       SET r.source = "SEAL", r.description = "Risk owner (SEAL).";
MERGE (r:Role {name:"CTO"})                SET r.source = "SEAL", r.description = "Chief technology officer for the application (SEAL).";
MERGE (r:Role {name:"Agility Lead"})       SET r.source = "PAT",  r.description = "Agile delivery lead for the application (PAT).";
MERGE (r:Role {name:"Software Engineer"})  SET r.source = "PAT",  r.description = "Engineer on the application's dev team (PAT, multi-valued).";
MERGE (r:Role {name:"Product Contact"})    SET r.source = "PAT",  r.description = "Product-level contact (PAT). Often overlaps CTO.";


// ----- SchedulerKind --------------------------------------------------------
//   Phase 1 only ingests Control-M, but the kinds vocabulary lets Applications
//   declare which orchestrators they require even when unused.
MERGE (k:SchedulerKind {name:"ControlM"}) SET k.kind_label = "BMC Control-M",  k.phase_supported = 1;
MERGE (k:SchedulerKind {name:"Autosys"})  SET k.kind_label = "CA Autosys",     k.phase_supported = 2;
MERGE (k:SchedulerKind {name:"Airflow"})  SET k.kind_label = "Apache Airflow", k.phase_supported = 2;


// ----- Corporate hierarchy: Company + BusinessSegments ----------------------
MERGE (jpmc:Company {name:"JPMC"})
  SET jpmc.legal_name = "JPMorgan Chase & Co.",
      jpmc.source     = "annual report";

// Post-Q2-2024 segments (current).
MERGE (s:BusinessSegment {code:"CCB"})  SET s.name = "Consumer & Community Banking";
MERGE (s:BusinessSegment {code:"CIB"})  SET s.name = "Commercial & Investment Bank";
MERGE (s:BusinessSegment {code:"AWM"})  SET s.name = "Asset & Wealth Management";
MERGE (s:BusinessSegment {code:"Corp"}) SET s.name = "Corporate";

// Pre-Q2-2024 segment retired (CB merged into CIB).
MERGE (s:BusinessSegment {code:"CB"})
  SET s.name    = "Commercial Banking (pre-Q2-2024, merged into CIB)",
      s.retired = true;

// Effective-dated edges Company -> BusinessSegment (post-reorg, open-ended).
MATCH (jpmc:Company {name:"JPMC"})
MATCH (s:BusinessSegment) WHERE s.code IN ['CCB','CIB','AWM','Corp']
MERGE (jpmc)-[r:HAS_BUSINESS_SEGMENT]->(s)
  ON CREATE SET r.effective_from = date('2024-04-01'),
                r.effective_to   = null,
                r.source         = "annual report";

// Pre-reorg snapshot (historical edge).
MATCH (jpmc:Company {name:"JPMC"})
MATCH (s:BusinessSegment) WHERE s.code IN ['CCB','CIB','CB','AWM']
MERGE (jpmc)-[r:HAS_BUSINESS_SEGMENT_HISTORICAL]->(s)
  ON CREATE SET r.effective_from = date('2010-01-01'),
                r.effective_to   = date('2024-03-31'),
                r.source         = "annual report (pre-Q2-2024)";


// ----- DQV catalog: Dimensions + Metrics (TDQ baseline, v2 §11.6) -----------
MERGE (d:Dimension {name:"Completeness"}) SET d.description = "Whether all required data is present.";
MERGE (d:Dimension {name:"Accuracy"})     SET d.description = "Whether values match a trusted source.";
MERGE (d:Dimension {name:"Consistency"})  SET d.description = "Whether values are consistent across structures and over time.";
MERGE (d:Dimension {name:"Timeliness"})   SET d.description = "Whether data arrives within the agreed SLA.";
MERGE (d:Dimension {name:"Integrity"})    SET d.description = "Whether structural / referential rules hold.";

// Metrics keyed by name; each links into one dimension.
MERGE (m:Metric {name:"rowcount_match"})        SET m.description = "Data file row count matches control file claim.";
MERGE (m:Metric {name:"null_rate"})             SET m.description = "Per-column null rate vs threshold.";
MERGE (m:Metric {name:"hash_match"})            SET m.description = "File SHA-256 matches control file hash.";
MERGE (m:Metric {name:"value_range"})           SET m.description = "Numeric values within configured min/max.";
MERGE (m:Metric {name:"schema_conformance"})    SET m.description = "Columns and types match the expected schema.";
MERGE (m:Metric {name:"referential_integrity"}) SET m.description = "Foreign keys resolve to existing rows.";
MERGE (m:Metric {name:"freshness_sla"})         SET m.description = "Arrival timestamp meets the dataset SLA.";
MERGE (m:Metric {name:"arrival_latency"})       SET m.description = "Time between expected and actual arrival.";
MERGE (m:Metric {name:"pkey_uniqueness"})       SET m.description = "Primary keys are unique.";
MERGE (m:Metric {name:"fkey_validity"})         SET m.description = "Foreign keys present in parent dataset.";

// Wire metrics to dimensions.
MATCH (m:Metric {name:"rowcount_match"}),        (d:Dimension {name:"Completeness"}) MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"null_rate"}),             (d:Dimension {name:"Completeness"}) MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"hash_match"}),            (d:Dimension {name:"Accuracy"})     MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"value_range"}),           (d:Dimension {name:"Accuracy"})     MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"schema_conformance"}),    (d:Dimension {name:"Consistency"})  MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"referential_integrity"}), (d:Dimension {name:"Consistency"})  MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"freshness_sla"}),         (d:Dimension {name:"Timeliness"})   MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"arrival_latency"}),       (d:Dimension {name:"Timeliness"})   MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"pkey_uniqueness"}),       (d:Dimension {name:"Integrity"})    MERGE (m)-[:IN_DIMENSION]->(d);
MATCH (m:Metric {name:"fkey_validity"}),         (d:Dimension {name:"Integrity"})    MERGE (m)-[:IN_DIMENSION]->(d);


// ----- Loader Agent (PROV) --------------------------------------------------
MERGE (a:Agent:SoftwareAgent {id:"drydocs.loader.v1"})
  SET a.label = "DryDocs Loader v1",
      a.kind  = "loader";