import diffData from '../generated/remediation-diff.json'

// The SME working-session diff (2026-08-12 ruling: the console diff is the
// working session; the change-doc excerpt is the packaging-time surface).
// Data is GENERATED by scripts/render_remediation_diff.py through the REAL
// xml_io splice + self-check pipeline over a SYNTHETIC demo folder — real fix
// diffs are Internal and company-side, and drydocs_remediation writes no
// graph, so there is no QuerySpec by design (same argument as the other
// /remediation frames). Drift guard: test_remediation_diff_json.py.
//
// No diff library: the renderer computes changed_line_numbers from the
// self-check (every changed line PROVEN to intersect an approved edit span),
// and this component only colors by the flag — the same
// producer-marks/consumer-styles split TowerDrill uses for Cypher.

interface DiffLine {
  n: number
  text: string
  changed: boolean
}

interface DiffChange {
  approval_id: string
  kind: string
  detail: string
  value: string | null
  evidence: string
  folder: string
}

interface DiffEffect {
  kind: string
  path: string
  detail: string
  old: string | null
  new: string | null
}

const DATA = diffData as {
  provenance: string
  fix_id: string
  verdict: string
  changed_line_numbers: number[]
  changes: DiffChange[]
  effects: DiffEffect[]
  before_lines: DiffLine[]
  after_lines: DiffLine[]
}

function Pane({ title, lines, tone }: { title: string; lines: DiffLine[]; tone: 'del' | 'add' }) {
  const mark = tone === 'del' ? 'bg-rose-500/15 text-rose-300' : 'bg-emerald-500/15 text-emerald-300'
  return (
    <div className="flex min-h-0 min-w-0 flex-1 flex-col rounded-md border border-edge">
      <p className="shrink-0 border-b border-edge bg-panel-2 px-2.5 py-1.5 font-mono text-[11px] font-semibold text-muted">
        {title}
      </p>
      <pre className="min-h-0 flex-1 overflow-auto p-2 font-mono text-[11px] leading-relaxed text-text">
        {lines.map((line) => (
          <div key={line.n} className={line.changed ? `${mark} -mx-2 px-2` : undefined}>
            <span className="mr-3 inline-block w-7 select-none text-right text-muted/60">{line.n}</span>
            {line.text || ' '}
          </div>
        ))}
      </pre>
    </div>
  )
}

export default function FixDiff() {
  return (
    <div className="flex h-full min-h-0 flex-col gap-1.5">
      <p className="shrink-0 rounded border border-yellow/50 bg-yellow/10 px-2 py-1 font-mono text-[10px] text-yellow">
        SYNTHESIZED demo folder · REAL mechanism (xml_io splice + self-check) · {DATA.provenance.split(';')[0]}
      </p>
      <div className="flex shrink-0 flex-wrap items-center gap-2 rounded border border-edge bg-panel-2 px-2.5 py-1.5 text-[11px]">
        <span className="font-mono font-semibold text-text">{DATA.fix_id}</span>
        <span
          className={
            'rounded px-1.5 py-0.5 font-mono text-[10px] font-semibold ' +
            (DATA.verdict === 'PASS' ? 'bg-emerald-500/15 text-emerald-300' : 'bg-rose-500/15 text-rose-300')
          }
        >
          self-check {DATA.verdict}
        </span>
        <span className="text-muted">
          {DATA.changed_line_numbers.length} changed line(s), every one proven inside an approved edit span
        </span>
      </div>
      {DATA.changes.map((c) => (
        <p key={c.approval_id} className="shrink-0 rounded border border-edge px-2.5 py-1 text-[11px] text-muted">
          <span className="font-mono font-semibold text-text">{c.approval_id}</span> · {c.kind}:{' '}
          <span className="font-mono">{c.detail}</span>
          {c.value ? (
            <>
              {' → '}
              <span className="font-mono">{c.value}</span>
            </>
          ) : null}{' '}
          — {c.evidence}
        </p>
      ))}
      <div className="flex min-h-0 flex-1 gap-1.5">
        <Pane title="original (evidence, untouched)" lines={DATA.before_lines} tone="del" />
        <Pane title="updated (minimal-diff full document)" lines={DATA.after_lines} tone="add" />
      </div>
      <details className="shrink-0 rounded border border-edge px-2.5 py-1 text-[11px] text-muted">
        <summary className="cursor-pointer select-none">
          every effect, enumerated ({DATA.effects.length})
        </summary>
        <ul className="mt-1 space-y-0.5 font-mono text-[10px]">
          {DATA.effects.map((e, i) => (
            <li key={i}>
              {e.kind} · {e.path} · {e.detail}
              {e.old !== null ? ` — was "${e.old}"` : ''}
              {e.new !== null ? ` now "${e.new}"` : ''}
            </li>
          ))}
        </ul>
      </details>
    </div>
  )
}
