// The G68 folder-set PROFILE the /remediation intake surface reads (O59).
//
// GENERATED by scripts/render_remediation_profile.py through the REAL
// profile() — the same census the `drydocs profile-folder-set` CLI verb
// writes — over a SYNTHETIC export. No QuerySpec, by design and not by
// omission: drydocs_remediation writes ZERO graph, so there is nothing for a
// spec to read, and minting :Finding / :FixBatch labels to make one would
// smuggle an ontology decision past the HITL gate (O17's deviation, which
// this item deliberately keeps rather than quietly reverses).
//
// Drift guard: tests/unit/test_remediation_profile_json.py.
//
// THE TYPES ARE HAND-DECLARED, not inferred from the JSON. Inferring would
// make every field's type "whatever the demo happens to carry" — an empty
// census would narrow a field to never, and a value that is null in the demo
// and a string in a real export would type-check here and break there.

import profileJson from '../generated/remediation-profile.json'

export interface ShapeCensus {
  data_centers: string[]
  folders: string[]
  subfolders: string[]
  jobs: number
  jobs_by_type: Record<string, number>
  /** Read off the sub-folder ladder. LABELLED inferred: a reading of the
   *  shape, not a declared fact, and the SME can correct it. */
  datasets_inferred: string[]
}

export interface IdentityRow {
  fact: string
  value: string
  jobs: string[]
  /** RUN_AS only. A FileWatcher on the platform account beside payload jobs on
   *  the application account is the DESIGNED pattern (SME, 2026-08-19); a flat
   *  list blurs that into "two accounts" and loses the finding. */
  job_types: string[]
}

export interface VariableRow {
  name: string
  scope: string
  containers: string[]
  distinct_values: number
  reference_count: number
  /** R31: declared at job scope, referenced nowhere on that job. */
  unreferenced: boolean
  /** R30: referenced somewhere, declared nowhere in the chain. */
  unresolved: boolean
}

export interface ContactRow {
  name: string
  value: string
  kind: string
  containers: string[]
  documentation_only: boolean
}

export interface InvocationRow {
  target: string
  invocation_type: string
  fan_out: number
  jobs: string[]
  varying_variables: string[]
  constant_variables: string[]
}

export interface SubstitutionSlot {
  name: string
  home: string
  rule: string
  status: 'present' | 'not-supplied'
  /** null, NEVER "". An absent value must be structurally distinguishable
   *  from a blank one carried by the export. */
  value: string | null
  applies_to: string[]
}

export interface Finding {
  rule_id: string
  severity: string
  ratified: boolean
  target: string
  message: string
}

export interface FolderSetProfile {
  source: string
  shape: ShapeCensus
  identity: IdentityRow[]
  variables: VariableRow[]
  contacts: ContactRow[]
  invocations: InvocationRow[]
  substitution_slots: SubstitutionSlot[]
  findings: Finding[]
  provenance: string
  summary: string
}

export const PROFILE = profileJson as unknown as FolderSetProfile

/** The banner every frame on this surface carries. */
export const PROFILE_NOTICE =
  'SYNTHETIC folder-set export · REAL mechanism (G68 profile()) — no graph, no QuerySpec by design'

/**
 * Did the profile COMPUTE this census, or is it simply absent?
 *
 * The frames' honesty rule (O56/O58, restated by O59) turns on this: a census
 * the profile did not compute must render "not profiled", never 0. The typed
 * view above cannot answer it — every field is declared, so TypeScript would
 * say yes for a key that is not in the file — so the raw object is asked.
 */
const RAW = profileJson as unknown as Record<string, unknown>

export function censusComputed(name: keyof FolderSetProfile): boolean {
  return RAW[name] !== undefined && RAW[name] !== null
}
