import lookupData from '../generated/remediation-lookup.json'

// G85: beside the SME fix diff, the answer to "why is this the rule?" and
// "does the vendor actually say that?" -- walked down the ratified precedence
// chain (config/precedence.yaml): vendor baseline, then internal standards,
// then who owns the thing. Every row is GENERATED by
// scripts/render_remediation_lookup.py, which resolves each citation against
// the corpus file it names and refuses to emit one it cannot find; this
// component only lays the chain out. It decides nothing -- the rules engine
// and the xml_io self-check already did -- and it writes nothing.
//
// Trust travels with every citation and is never restyled into certainty: a
// search-snippet lead reads as a lead, and a tier with nothing citable renders
// its gap and the reason, not an empty box.

interface Citation {
  doc: string
  line: number
  section: string
  excerpt: string
  trust: string
  citable_as: string
  captured: string | null
  source_url: string | null
}

interface Gap {
  what: string
  reason: string
}

interface TierAnswer {
  tier: string
  status: 'cited' | 'gap'
  citations: Citation[]
  gaps: Gap[]
}

interface Lookup {
  approval_id: string
  kind: string
  subject: string
  answers: TierAnswer[]
}

interface Tier {
  id: string
  authority_id: string
  authority: number
  title: string
  question: string
  source: string
}

const DATA = lookupData as {
  provenance: string
  fix_id: string
  agent_seam: string
  tiers: Tier[]
  lookups: Lookup[]
}

function trustTone(trust: string): string {
  if (trust === 'VERBATIM' || trust === 'GROUNDED') return 'border-emerald-500/50 text-emerald-300'
  if (trust === 'GROUNDED-snippets-only') return 'border-yellow text-yellow'
  return 'border-faint text-faint'
}

function CitationRow({ c }: { c: Citation }) {
  return (
    <li className="rounded border border-edge px-2 py-1" data-lookup-trust={c.trust}>
      <p className="flex flex-wrap items-center gap-1.5 font-mono text-[10px] text-muted">
        <span className="text-text">
          {c.doc}:{c.line}
        </span>
        <span>· {c.section}</span>
        <span className={`rounded-xs border px-1 ${trustTone(c.trust)}`} title={c.citable_as}>
          {c.trust}
        </span>
        {c.captured ? <span>captured {c.captured}</span> : null}
      </p>
      <p className="mt-0.5 border-l-2 border-edge pl-2 text-[11px] text-text">{c.excerpt}</p>
      <p className="mt-0.5 text-[10px] text-faint">{c.citable_as}</p>
    </li>
  )
}

export default function RemediationLookup() {
  const tiers = new Map(DATA.tiers.map((t) => [t.id, t]))
  return (
    <aside
      className="flex h-full min-h-0 flex-col gap-1.5 overflow-auto"
      aria-label="Why this change: vendor, then standards, then team"
    >
      <p className="shrink-0 rounded border border-edge bg-panel-2 px-2 py-1 font-mono text-[10px] text-muted">
        {DATA.provenance}
      </p>
      {DATA.lookups.map((lookup) => (
        <section key={lookup.approval_id} className="rounded-md border border-edge" data-lookup={lookup.approval_id}>
          <p className="border-b border-edge bg-panel-2 px-2.5 py-1.5 text-[11px] text-muted">
            <span className="font-mono font-semibold text-text">{lookup.approval_id}</span> · {lookup.kind}:{' '}
            <span className="font-mono">{lookup.subject}</span>
          </p>
          <ol className="space-y-2 p-2">
            {lookup.answers.map((answer, i) => {
              const tier = tiers.get(answer.tier)
              return (
                <li key={answer.tier} data-lookup-tier={answer.tier} data-lookup-status={answer.status}>
                  <p
                    className="text-[11px] font-semibold text-text"
                    title={tier ? `authority ${tier.authority} (${tier.authority_id}) in config/precedence.yaml` : undefined}
                  >
                    {i + 1}. {tier?.title}{' '}
                    <span className="font-normal text-muted">— {tier?.question}</span>
                  </p>
                  {answer.citations.length > 0 ? (
                    <ul className="mt-1 space-y-1">
                      {answer.citations.map((c) => (
                        <CitationRow key={`${c.doc}:${c.line}`} c={c} />
                      ))}
                    </ul>
                  ) : null}
                  {answer.gaps.map((g) => (
                    <p
                      key={g.what}
                      className="mt-1 rounded border border-dashed border-faint px-2 py-1 text-[11px] text-muted"
                      data-lookup-gap
                    >
                      <span className="font-semibold text-text">Not answerable here:</span> {g.what} — {g.reason}
                    </p>
                  ))}
                </li>
              )
            })}
          </ol>
        </section>
      ))}
      <p className="shrink-0 text-[10px] text-faint">{DATA.agent_seam}</p>
    </aside>
  )
}
