"""Write a THROWAWAY console credential for the end-to-end suite (O80).

WHY THIS EXISTS RATHER THAN A FLAG ON THE OPERATOR SCRIPT. ``scripts/
set_console_credential.py`` takes its secret through ``getpass`` by
construction, and that is a design property rather than an oversight: O76's
provenance record distinguishes a PROMPTED secret, which was never rendered
anywhere a screen share could catch it, from a GENERATED one, which was printed
to a terminal once and is therefore flagged for rotation. Adding a
``--secret-from-env`` flag for CI's benefit would put a third, unrecorded origin
into the operator's own tool and weaken the record for every real machine. So
the test harness gets its own entry point and the operator script keeps its
guarantee.

WHAT IT WRITES, AND WHERE IT CANNOT REACH. The path comes from
``DRYDOCS_CONSOLE_CREDENTIALS``, which the harness points at a temp directory,
never at ``internal-local/``. This script REFUSES to run against the default
location for exactly that reason — a test fixture must not be able to overwrite
the credential a person signs in with on their own desktop. The secret comes
from ``DRYDOCS_E2E_SECRET``, generated per run by the harness and never stored
in the repo.

The origin is recorded as ``generated``, which is the truth: it was generated by
a machine and handed to a process. Nothing rotates it because nothing keeps it —
the file is deleted with its temp directory when the run ends.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from drydocs_api.credentials import (  # noqa: E402 — after the sys.path fix above
    DEFAULT_RELATIVE_PATH,
    ORIGIN_GENERATED,
    CredentialStore,
)
from drydocs_core.repo_paths import repo_root  # noqa: E402
from scripts.set_console_credential import save_store  # noqa: E402

#: The persona the suite signs in as. Deliberately the admin seat: the e2e path
#: reaches a module in the nav, and a user-tier seat renders a smaller nav, so a
#: nav assertion would be testing the role rather than the runner.
E2E_PERSONA = "morpheus"


def main() -> int:
    target = os.environ.get("DRYDOCS_CONSOLE_CREDENTIALS")
    secret = os.environ.get("DRYDOCS_E2E_SECRET")
    if not target or not secret:
        print(
            "refused: DRYDOCS_CONSOLE_CREDENTIALS and DRYDOCS_E2E_SECRET must both be set; "
            "this script is driven by the Playwright harness, not run by hand",
            file=sys.stderr,
        )
        return 2

    path = Path(target).resolve()
    # Compared against the DEFAULT location, never against ``credentials_path()``:
    # that helper honours DRYDOCS_CONSOLE_CREDENTIALS, which the harness has just
    # set to the temp path, so it would compare the temp path with itself and
    # refuse every run. The guard's subject is the file a person actually signs in
    # with, and that file's location is the default one.
    real = (repo_root(REPO) / DEFAULT_RELATIVE_PATH).resolve()
    if path == real:
        print(
            f"refused: {path} is this machine's REAL credential file. The e2e harness "
            "writes to a temp path; overwriting a person's own console secret to run a "
            "test would be a defect, not a convenience.",
            file=sys.stderr,
        )
        return 2

    store = CredentialStore.load(path)
    store.set(E2E_PERSONA, secret, origin=ORIGIN_GENERATED)
    save_store(store, path)
    print(f"e2e credential written for {E2E_PERSONA} -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
