"""Generate `.env.example` from the declared variable list (G129 (b)).

    poetry run python scripts/render_env_example.py
    poetry run python scripts/render_env_example.py --check

WHY THIS IS GENERATED AND NOT WRITTEN. The hand-maintained file declared 17 keys
while first-party code read eight more that were declared nowhere at all -- the
console credential path, the Control-M adapter config pointer, both mapping-store
variables, the agent registration key, the caller variable, the Neo4j container
name, and the two legacy aliases. Nothing could have caught that: the file was
prose, and prose has no guard. Generating it from
:data:`drydocs_core.env_refs.DECLARED_VARIABLES` makes the gap impossible to
reopen, because a variable that is not declared cannot be referenced by a binding
(``expand`` refuses it) and a variable that IS declared lands in this file
automatically.

NO VALUE IS EMITTED FOR A SECRET, and that is enforced upstream rather than here:
:class:`~drydocs_core.env_refs.EnvVar` refuses a declaration that pairs
``secret=True`` with an ``example``. The rule belongs at the declaration because
this renderer is not the only thing that could read one, and a placeholder
password in a template is a password somebody eventually ships.

THE PORT CONSEQUENCE, stated because it changes how the consumer takes this file.
`.env.example` is `per-entry` in PORT-MANIFEST.yaml with "union on collision" --
the consumer adds its own keys (Kerberos, RAC). Those additions now belong in the
DECLARATION, not in this file: an edit here is overwritten by the next render,
and a key added here alone is a key no binding may reference.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from drydocs_core.env_refs import (  # noqa: E402 -- after the sys.path fix above
    DECLARED_VARIABLES,
    GROUPS,
    EnvVar,
)

TARGET = REPO_ROOT / ".env.example"

#: Pinned: this file commits as LF, and a CRLF write against an LF index leaves
#: the stale-render check permanently dirty while no blob ever changes
#: (Idea-121, guarded by tests/unit/test_render_determinism.py).
NEWLINE = "\n"

RULE = "# " + "-" * 75

HEADER = """\
# =============================================================================
# DryDocs -- environment variables template
#
# GENERATED from drydocs_core/env_refs.py. Do not edit this file: run
#     poetry run python scripts/render_env_example.py
# after changing a declaration. A key added here alone is a key no binding may
# reference, because config/source-bindings.yaml resolves through the declared
# list and nothing else (ADR 0017 clause 3, G125).
#
# Copy to `.env` and fill in values; `.env` is gitignored. To set one without it
# reaching your shell history, the process table, or a screen share:
#     poetry run python scripts/set_env_var.py <NAME>
# To see what is set on this machine without printing any value:
#     poetry run drydocs env-doctor
# ============================================================================="""


def _lines_for(var: EnvVar) -> list[str]:
    out: list[str] = []
    out.append(f"# {var.purpose}.")
    if var.aliases:
        out.append(f"# Deprecated alias(es), still honored: {', '.join(var.aliases)}.")
    if var.required:
        out.append("# REQUIRED -- there is no default and an unset value fails naming it.")
    if var.secret:
        out.append("# SECRET -- masked wherever the system prints, and never given an example.")
    for line in var.doc.splitlines():
        out.append(f"# {line}" if line else "#")
    out.append(f"{var.name}={var.example}")
    return out


def render() -> str:
    """The whole file, as a string. Pure -- it reads no environment and no clock."""
    by_group: dict[str, list[EnvVar]] = {}
    for var in DECLARED_VARIABLES:
        by_group.setdefault(var.group, []).append(var)

    parts: list[str] = [HEADER]
    for key, heading in GROUPS:
        members = by_group.get(key, [])
        if not members:
            continue
        parts.append("")
        parts.append(RULE)
        parts.append(f"# {heading}")
        parts.append(RULE)
        for var in members:
            parts.append("")
            parts.extend(_lines_for(var))
    return NEWLINE.join(parts).rstrip(NEWLINE) + NEWLINE


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate .env.example from the declarations.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when the committed file differs from a fresh render",
    )
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.name} is stale -- re-run without --check", file=sys.stderr)
            return 1
        print(f"{TARGET.name} matches the declarations")
        return 0

    TARGET.write_text(rendered, encoding="utf-8", newline=NEWLINE)
    print(f"wrote {TARGET.relative_to(REPO_ROOT).as_posix()} ({len(DECLARED_VARIABLES)} keys)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
