"""render_remediation_diff.py — the /remediation fix-diff frame (SME working session).

Emits ``web/src/generated/remediation-diff.json``: a before/after Control-M
folder XML diff produced by the REAL pipeline — ``xml_io`` load → approved
change-set compile → splice → three-layer self-check — over a SYNTHETIC demo
folder. Real fix diffs carry real folder/job values, are Internal, and are
company-side; what this frame demonstrates (and what the drift guard pins) is
the MECHANISM: a minimal-diff full document, every changed line intersecting
an approved edit span, every effect enumerated with its approval id.

Consumed by ``web/src/routes/RemediationRoute.tsx``. Drift guard:
``tests/unit/test_remediation_diff_json.py`` (importlib-loads this file and
asserts committed == build_remediation_diff()). Registered in
``render_board.py``'s default-paths run — an unregistered artifact silently
drifts (the J20 incident).

Determinism notes: no timestamps, no randomness; sort keys where order is not
meaningful; strings only (the UI needs no bytes).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from drydocs_remediation.changes import ApprovedChange, compile_changes  # noqa: E402
from drydocs_remediation.xml_io import Locator, load_document, render, self_check  # noqa: E402

OUT = REPO / "web" / "src" / "generated" / "remediation-diff.json"

#: SYNTHETIC demo folder — invented names, deliberately carrying the surfaces
#: defect A′ used to miss (CMDLINE, POSTCMD, DESCRIPTION, folder scope,
#: residue elements) so the demo diff SHOWS the sweep reaching all of them.
DEMO_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<DEFTABLE>
  <SMART_FOLDER DATACENTER="DC-DEMO" FOLDER_NAME="PRDEMO1A"
                DESCRIPTION="demo series - %%SCRIPT_PATH launcher pattern">
    <VARIABLE NAME="%%SCRIPT_PATH" VALUE="/apps/dpl"/>
    <JOB JOBNAME="PRDEMO1A001" TASKTYPE="Command"
         DESCRIPTION="runs %%SCRIPT_PATH nightly"
         CMDLINE="%%SCRIPT_PATH/run.sh -env %%ENV"
         POSTCMD="cat %%SCRIPT_PATH/out.tok">
      <VARIABLE NAME="%%ENV" VALUE="prod"/>
      <INCOND NAME="PRDEMO1A000-OK" ODATE="ODAT" AND_OR="AND"/>
      <OUTCOND NAME="PRDEMO1A001-OK" ODATE="ODAT" SIGN="ADD"/>
      <ON STMT="*" CODE="NOTOK">
        <DOMAIL DEST="ops-dl" SUBJECT="failed under %%SCRIPT_PATH"/>
      </ON>
    </JOB>
  </SMART_FOLDER>
</DEFTABLE>
"""

DEMO_CHANGES = [
    ApprovedChange(
        approval_id="gate-demo-1",
        kind="rename-variable",
        locator=Locator(folder="PRDEMO1A"),
        detail="SCRIPT_PATH",
        value="LAUNCHER_SCRIPT_PATH",
        evidence="ratified canonical name (cmdline-nfr-vetting standard); "
        "the sweep rewrites EVERY surface, residue included",
    ),
]


def build_remediation_diff() -> dict:
    """The whole frame, computed by the real pipeline. Pure; no I/O."""
    doc = load_document(DEMO_XML)
    script, effects = compile_changes(doc, DEMO_CHANGES)
    updated = render(doc, script.compile())
    report = self_check(doc, script, updated)

    before_lines = DEMO_XML.decode("utf-8").splitlines()
    after_lines = updated.decode("utf-8").splitlines()
    changed = set(report.changed_line_numbers)

    return {
        "note": (
            "GENERATED by scripts/render_remediation_diff.py — never hand-edit; "
            "regenerate with a default-paths render_board.py run"
        ),
        "provenance": (
            "SYNTHESIZED demo data through the REAL mechanism (xml_io splice + "
            "three-layer self-check). Real fix diffs are Internal and company-side; "
            "drydocs_remediation writes no graph, so there is no QuerySpec by design."
        ),
        "fix_id": "FIX-DEMO-001",
        "verdict": "PASS" if report.ok else "FAILED",
        "changed_line_numbers": sorted(changed),
        "changes": [
            {
                "approval_id": c.approval_id,
                "kind": c.kind,
                "detail": c.detail,
                "value": c.value,
                "evidence": c.evidence,
                "folder": c.locator.folder,
            }
            for c in DEMO_CHANGES
        ],
        "effects": [
            {"kind": e.kind, "path": e.path, "detail": e.detail, "old": e.old, "new": e.new}
            for e in effects
        ],
        "before_lines": [
            {"n": i + 1, "text": line, "changed": (i + 1) in changed}
            for i, line in enumerate(before_lines)
        ],
        "after_lines": [
            {"n": i + 1, "text": line, "changed": (i + 1) in changed}
            for i, line in enumerate(after_lines)
        ],
    }


def main() -> None:
    data = build_remediation_diff()
    OUT.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    print(
        f"wrote {OUT} ({len(data['effects'])} effect(s), "
        f"{len(data['changed_line_numbers'])} changed line(s), verdict {data['verdict']})"
    )


if __name__ == "__main__":
    main()
