"""render_console_personas.py — the console roster, from the declaration to the console.

CFG14. Reads ``config/console-personas.yaml`` through
``drydocs_core.console_personas`` and writes
``web/src/generated/console-personas.json``, which ``web/src/lib/auth.ts`` imports
the way ``loadMapModel.ts`` imports ``load-map.json``.

Deterministic by construction: the roster is emitted in declaration order (the
file's own order, which is the order the sign-in screen lists seats in), the JSON
is written with a fixed indent and a trailing newline, and nothing here reads a
clock or the environment. Two runs over one declaration produce one file.

WHAT IS EMITTED, AND WHAT IS NOT. The seats and their roles go; the claim block
does NOT. It is deferred and empty, the console has no use for it, and shipping an
empty mapping to the browser would invite a reader to treat it as the entitlement
source it is explicitly not yet. When P4's trigger fires and the mapping is
populated, whether the console needs any of it is that build's question.

Usage:
    python scripts/render_console_personas.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from drydocs_core.console_personas import ConsolePersonas  # noqa: E402

OUT = REPO / "web" / "src" / "generated" / "console-personas.json"


def build(personas: ConsolePersonas | None = None) -> dict:
    """The generated payload. Pure: takes the reader, returns the document."""
    roster = personas if personas is not None else ConsolePersonas.from_yaml()
    return {
        "note": (
            "GENERATED by scripts/render_console_personas.py from "
            "config/console-personas.yaml (CFG14). Do not edit: the declaration is "
            "the source, and this file is overwritten at every render. This is the "
            "DEMO ROSTER and not an authorization source - the server re-resolves "
            "the real role from the bearer token on every request (ADR 0005 d3)."
        ),
        "roles": list(roster.roles),
        "personas": roster.as_rows(),
    }


def main() -> int:
    doc = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # ensure_ascii=False to match render_load_map and render_gates: the chips carry
    # middots, and an escaped one is unreadable in a diff for no gain.
    OUT.write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"wrote {OUT} ({len(doc['personas'])} personas, {len(doc['roles'])} roles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
