"""Generate the O19 /gates page data (the O12 enforcement-matrix pattern).

Scans config/gate-log.md (one row per ``## `` entry), config/gate-prompts/
(one row per prompt file, joined to log entries by slug mention), and
backlog.yaml (which items mention each gate slug -> the "unblocks" edges of
the gate dependency graph) and emits ``web/src/generated/gates.json``.
``tests/unit/test_gates_json.py`` is the drift guard: a gate-log entry or
gate-prompt file with no row fails the build.

Status vocabulary (derived from the log verbatim -- the page renders the
record, it never reinterprets it):
- ``open``       -- a gate-prompt file with NO gate-log section mentioning it
                    (rendered/pending session).
- ``deferred``   -- the entry heading says DEFERRED.
- ``pending``    -- the entry heading says PENDING (a later entry may resolve
                    it; rows reflect the log as written).
- ``signed-off`` -- the heading says SIGNED OFF / ACCEPTED / CONFIRMED.
- ``recorded``   -- everything else (decisions logged without the formal
                    sign-off wording, e.g. early C1-C4 entries).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
LOG = REPO / "config" / "gate-log.md"
PROMPTS = REPO / "config" / "gate-prompts"
BACKLOG = REPO / "docs" / "restructure" / "backlog.yaml"
OUT = REPO / "web" / "src" / "generated" / "gates.json"

_HEADING_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})(?:[^\S\n]*[—-][^\S\n]*)(.+)$", re.MULTILINE)


def _status_for(heading: str) -> str:
    up = heading.upper()
    if "DEFERRED" in up:
        return "deferred"
    if "PENDING" in up:
        return "pending"
    if "SIGNED OFF" in up or "ACCEPTED" in up or "CONFIRMED" in up:
        return "signed-off"
    return "recorded"


def build_gates() -> dict:
    log_text = LOG.read_text(encoding="utf-8")
    backlog_items = yaml.safe_load(BACKLOG.read_text(encoding="utf-8"))["items"]

    # split the log into (date, heading, body) sections
    sections: list[dict] = []
    matches = list(_HEADING_RE.finditer(log_text))
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(log_text)
        sections.append(
            {
                "date": m.group(1),
                "heading": m.group(2).strip(),
                "body": log_text[m.end() : end],
                "line": log_text.count("\n", 0, m.start()) + 1,
            }
        )

    prompt_slugs = sorted(p.stem for p in PROMPTS.glob("*.yaml"))

    def unblocks(slug_or_words: list[str]) -> list[str]:
        ids = []
        for item in backlog_items:
            text = json.dumps(item, ensure_ascii=False, default=str)
            if any(w in text for w in slug_or_words):
                ids.append(item["id"])
        return ids

    rows: list[dict] = []
    matched_slugs: set[str] = set()

    for s in sections:
        # join prompt files whose slug appears in the heading or section body
        slugs = [p for p in prompt_slugs if p in s["heading"] or p in s["body"]]
        matched_slugs.update(slugs)
        search_terms = slugs if slugs else []
        rows.append(
            {
                "kind": "log-entry",
                "date": s["date"],
                "title": s["heading"],
                "status": _status_for(s["heading"]),
                "prompt_files": [f"config/gate-prompts/{p}.yaml" for p in slugs],
                "log_ref": f"config/gate-log.md:{s['line']}",
                "unblocks": unblocks(search_terms) if search_terms else [],
            }
        )

    for p in prompt_slugs:
        if p not in matched_slugs:
            rows.append(
                {
                    "kind": "prompt-only",
                    "date": None,
                    "title": f"{p} (gate page rendered — session not yet run)",
                    "status": "open",
                    "prompt_files": [f"config/gate-prompts/{p}.yaml"],
                    "log_ref": None,
                    "unblocks": unblocks([p]),
                }
            )

    return {
        "note": (
            "GENERATED by scripts/render_gates.py -- never hand-edit. "
            "tests/unit/test_gates_json.py fails when this drifts from the record. "
            "The page renders the gate RECORD read-only; acting on gates from the "
            "UI is exactly what the O20 gate decides."
        ),
        "gates": rows,
    }


def main() -> int:
    data = build_gates()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    open_n = sum(1 for g in data["gates"] if g["status"] in ("open", "deferred", "pending"))
    print(f"wrote {OUT} ({len(data['gates'])} gates, {open_n} open/deferred/pending)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
