"""Drift guard for web/src/generated/remediation-profile.json (O59).

The artifact is GENERATED by scripts/render_remediation_profile.py through the
REAL G68 ``profile()`` over a synthetic export, so this guard is double-duty the
same way the fix-diff guard is: it catches a stale committed copy AND it catches a
census or detector change that alters what the mechanism produces (either way,
regenerate and review the diff).

The other guards here pin the properties the CONSOLE relies on, and each exists
because the frame makes a promise a plain "it matches" check cannot keep:

* the two failure classes must both be PRESENT in the demo data, or the findings
  frame demonstrates its own headline claim with an empty section;
* an absent slot must be structurally unfakeable — ``not-supplied`` AND ``null``,
  never ``""`` — because the frame renders "not supplied" off that and a blank
  string would render as a supplied empty value;
* every census the frame reads must exist as a key, since the frame's honesty rule
  is that a census the profile did not compute renders "not profiled" rather than 0
  — and it can only do that if a missing census is missing rather than empty.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RENDERER = REPO / "scripts" / "render_remediation_profile.py"
COMMITTED = REPO / "web" / "src" / "generated" / "remediation-profile.json"

#: The frame's sections. Named here rather than derived, so DELETING a census
#: from the profile fails this guard instead of silently emptying a frame.
CENSUSES = ("shape", "identity", "variables", "contacts", "invocations")


def _load_renderer():
    spec = importlib.util.spec_from_file_location("render_remediation_profile", RENDERER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _committed() -> dict:
    return json.loads(COMMITTED.read_text(encoding="utf-8"))


def test_committed_profile_matches_regeneration() -> None:
    assert _committed() == _load_renderer().build_remediation_profile(), (
        "web/src/generated/remediation-profile.json is stale — re-run "
        "`python scripts/render_remediation_profile.py` (or a default-paths "
        "render_board.py run) and commit the refresh"
    )


def test_every_census_the_frame_reads_is_present() -> None:
    committed = _committed()
    missing = [
        name for name in (*CENSUSES, "substitution_slots", "findings") if name not in committed
    ]
    assert not missing, f"the console reads censuses the artifact does not carry: {missing}"


def test_both_failure_classes_are_demonstrated() -> None:
    """The findings frame's whole claim is that it does not flatten them.

    R2 is the SILENCE class (the drifted name misses the fact registry, so NO row
    is written and the lineage is absent); R34 is the CONFIDENTLY WRONG class (the
    name resolves, so a row IS written, carrying a false value). Both spellings are
    detect.py's own, from its module docstring. A demo carrying only one of them
    would render an empty section beside a full one and teach the reader the
    opposite of the point.
    """
    rules = {f["rule_id"] for f in _committed()["findings"]}
    assert "R2" in rules, "no name-drift finding — the SILENCE class section would be empty"
    assert (
        "R34" in rules
    ), "no value-contract finding — the CONFIDENTLY WRONG section would be empty"


def test_the_confidently_wrong_class_outranks_the_silent_one() -> None:
    """detect.py files R34 as must-fix and R2 below it, and the frame ranks by
    that. Pinned here because the ranking is the triage lesson, not a style."""
    by_rule = {f["rule_id"]: f["severity"] for f in _committed()["findings"]}
    assert by_rule["R34"] == "must-fix"
    assert by_rule["R2"] != "must-fix"


def test_an_absent_slot_is_structurally_unfakeable() -> None:
    """G68's clause, re-asserted at the surface that renders it: a slot with no
    value carries status not-supplied AND value null — never "" and never a
    placeholder. The frame prints "not supplied" off exactly this."""
    for slot in _committed()["substitution_slots"]:
        if slot["status"] == "not-supplied":
            assert slot["value"] is None, f"{slot['name']} fakes an absent value"
        else:
            assert slot["value"], f"{slot['name']} claims present with no value"


def test_the_demo_carries_both_supplied_and_unsupplied_slots() -> None:
    """A form where every row is the same state demonstrates neither branch."""
    statuses = {slot["status"] for slot in _committed()["substitution_slots"]}
    assert statuses == {"present", "not-supplied"}


def test_every_slot_names_its_rule_and_the_jobs_it_applies_to() -> None:
    """The acceptance's "shape rule shown beside the input" and "the affected job
    count" both read straight off the artifact — neither is composed in the UI."""
    for slot in _committed()["substitution_slots"]:
        assert slot["rule"].strip(), f"{slot['name']} has no shape rule to show"
        assert slot["applies_to"], f"{slot['name']} applies to no jobs"


def test_the_run_as_census_reports_by_job_type() -> None:
    """The 2026-08-19 SME evidence, carried through to the surface: a FileWatcher
    on the platform account beside payload jobs on the application account is the
    DESIGNED pattern, and a flat list blurs it into "two accounts"."""
    run_as = [row for row in _committed()["identity"] if row["fact"] == "RUN_AS"]
    assert len(run_as) >= 2, "the demo no longer shows the two-account split"
    assert all(row["job_types"] for row in run_as), "run_as rows lost their job types"


def test_the_demo_is_synthetic() -> None:
    """Real folder sets carry real FIDs, SEALs and DLs and are Internal (J23).

    Checked on the artifact rather than trusted to the renderer's docstring: the
    addresses are reserved-invalid, and the SEAL sits in the 70001-70099 block the
    fixtures reserve.
    """
    blob = COMMITTED.read_text(encoding="utf-8")
    assert "@" not in blob or "example.invalid" in blob
    for line in blob.splitlines():
        if "@" in line and "example.invalid" not in line:
            raise AssertionError(f"a non-reserved address reached the artifact: {line.strip()}")
    seals = [row["value"] for row in _committed()["identity"] if row["fact"] == "SEAL"]
    assert all(70001 <= int(s) <= 70099 for s in seals), f"SEAL outside the reserved block: {seals}"
