"""Drift guard for web/src/generated/remediation-diff.json.

The frame is GENERATED by scripts/render_remediation_diff.py through the REAL
xml_io pipeline over a synthetic demo folder — so this guard is double-duty:
it catches a stale committed artifact AND it catches a mechanism change that
alters what the splice/self-check produces (either way, regenerate and review
the diff of the diff).
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RENDERER = REPO / "scripts" / "render_remediation_diff.py"
COMMITTED = REPO / "web" / "src" / "generated" / "remediation-diff.json"


def _load_renderer():
    spec = importlib.util.spec_from_file_location("render_remediation_diff", RENDERER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_frame_matches_regeneration() -> None:
    committed = json.loads(COMMITTED.read_text(encoding="utf-8"))
    fresh = _load_renderer().build_remediation_diff()
    assert committed == fresh, (
        "web/src/generated/remediation-diff.json is stale — re-run "
        "`python scripts/render_remediation_diff.py` (or a default-paths "
        "render_board.py run) and commit the refresh"
    )


def test_frame_is_produced_by_a_passing_self_check() -> None:
    """The committed demo must never ship a failing verdict: the frame's whole
    claim is 'this is what a self-checked minimal diff looks like'."""
    committed = json.loads(COMMITTED.read_text(encoding="utf-8"))
    assert committed["verdict"] == "PASS"
    assert committed["changed_line_numbers"], "a diff frame with no diff demonstrates nothing"


def test_every_changed_line_carries_the_flag_on_both_sides() -> None:
    """The UI colors by the `changed` flag; it must agree with the line list."""
    committed = json.loads(COMMITTED.read_text(encoding="utf-8"))
    changed = set(committed["changed_line_numbers"])
    for side in ("before_lines", "after_lines"):
        flagged = {row["n"] for row in committed[side] if row["changed"]}
        assert flagged == changed, f"{side} flags disagree with changed_line_numbers"


def test_every_effect_is_attributed_to_an_approval() -> None:
    """§XML rule 3 surfaces in the UI too: the frame's changes each carry an
    approval id, and the effects section is non-empty when lines changed."""
    committed = json.loads(COMMITTED.read_text(encoding="utf-8"))
    assert all(c["approval_id"] for c in committed["changes"])
    assert committed["effects"], "changed lines with no enumerated effects"
